spring.application.name=mouseion

# database configuratie
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/mouseionarchive
spring.datasource.username=postgres
spring.datasource.password=geheim
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# create-drop: bij elke start van de applicatie worden alle tabellen opnieuw gemaakt,
# en oude testdata verwijderd (handig voor testen of tijdens ontwikkeling).
# pas dit aan naar 'update' om bestaande tabellen en data te blijven behouden.
# update: handig als persistente testdata of echte date behouden moet blijven,
# zoals: spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
